# Generated by Django 5.1.6 on 2025-02-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='assigned_to',
        ),
    ]
