# Generated by Django 5.1.6 on 2025-02-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_incident_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
