# Generated by Django 5.1.6 on 2025-02-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Needs Review', 'Needs Review'), ('Needs Assistance', 'Needs Assistance'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
    ]
